package br.senac.procuratio.modelo.enumeracao.escolaridade;

public enum Escolaridade {
	ANALFABETO, ENSINO_FUNDAMENTAL_INCOMPLETO, ENSINO_FUNDAMENTAL_COMPLETO, ENSINO_MEDIO_INCOMPLETO, ENSINO_MEDIO_COMPLETO, ENSINO_SUPERIOR_INCOMPLETO, ENSINO_SUPERIOR_COMPLETO, POS_GRADUACAO_INCOMPLETO, POS_GRADUACAO_COMPLETO, DOUTORADO_INCOMPLETO, DOUTORADO_COMPLETO;
}